apiVersion: v1
kind: Secret
metadata:
  name: entra-oauth2-proxy
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  client-id: '${ENTRA_CLIENT_ID}'
  client-secret: '${ENTRA_CLIENT_SECRET}'
  tenant-id: '${ENTRA_TENANT_ID}'
  cookie-secret: '${OAUTH2_PROXY_COOKIE_SECRET}'
