apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: care-arrangement-plan-analytics-dev
spec:
  selector:
    app: care-arrangement-plan-analytics-dev
  ports:
    - port: 8501
      targetPort: 8501
      name: http
