apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: pfl-analytics-prod
spec:
  selector:
    app: pfl-analytics-prod
  ports:
    - port: 8501
      targetPort: 8501
      name: http
