apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_NAMESPACE}-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${KUBE_NAMESPACE}
spec:
  ports:
    - port: 8501
      name: http
  selector:
    app: ${KUBE_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-service
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: oauth2-proxy
spec:
  ports:
    - port: 4180
      name: http
  selector:
    app: oauth2-proxy
