name: Deploy to Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validation.yml
    secrets: inherit

  image:
    name: 'Build & Push Image'
    if: false
    needs: [validate]
    uses: ./.github/workflows/build-push-image.yml
    secrets: inherit

  deploy_dev:
    name: 'Deploy to Development'
    if: false
    uses: ./.github/workflows/deploy.yml
    needs: [image]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit
